EvictionLab/eviction-lab-website

- site/config.toml
- src/sass/_index.scss
Updating the configuration for the summary length, and moving the padding to the `p` tag instead of the answer div so that the expand/collapse animation isn't as choppy. Gif example below (but the gif is a bit choppy so not sure you can fully tell)
> Fix accordion transition, summary length

- site/layouts/partials/footer.html
- site/layouts/updates/single.html
- site/static/js/social-share-popup.js
- yarn.lock
Closes #73. Makes blog social share links usable. Facebook throws an error if the URL passed is invalid, but once we set `baseURL` in the configuration this will resolve itself. Right now I have them opening in another tab rather than in a popup window, but I can update it to be a popup window if we want
Also fixes an error I was getting where this template wouldn't build because it didn't check for whether `.Next` and `.Prev` were available before referencing them
> Add social share to blog posts

- site/layouts/partials/header.html
- site/themes/behave/layouts/partials/header.html
I was getting an error about this locally, so I added it to any heading template. Ignore any failing build that's using `rake`. It looks like it defaults to Ruby while the `.travis.yml` file isn't merged in
> Specify utf-8 charset in header

- site/layouts/index.html
- site/layouts/partials/footer.html
- site/static/js/mobile-vh-fix.js
- site/themes/behave/layouts/index.html
- src/sass/_utils.scss
- src/sass/main-sass.scss
Closes #91. In order to prevent weird scrolling behavior, you can just add the `mobile-vh` class to any element using `vh` and it will prevent resizing on mobile scroll. You can try it out here to see the difference https://fix-mobile-vh--eviction-lab.netlify.com/
> Add mobile-vh class to fix mobile vh transitions

- .travis.yml
Closes #2. Runs the build script for all branches, but only deploys `cms-dev` to staging and `master` to the main production bucket. Deploying to master also invalidates that CloudFront distribution's cache
> Add Travis deployment setup

- site/static/js/smooth-scroll.js
Only returns false in smooth scroll function if the element does not have the class `dropdown-item` so that dropdowns still close after clicking
> Fix bootstrap dropdown smoothscroll

- site/config.toml
- site/layouts/robots.txt
Adds robots.txt file telling search engines not to index the site. It hasn't happened yet, so nothing to worry about, but we can just remove the "Disallow" line once we launch
> Add robots.txt disallowing all

- site/layouts/partials/about-modal.html
Closes #111. The variable scoping for Hugo is a bit weird, so I repeated the creation of the Next button which is a little redundant, but this should work
> Modal loops back to first record on end

- site/config.toml
- site/layouts/partials/top.html
- src/sass/_menu.scss
Closes #119. Initial implementation of translate button. The CSS could probably be cleaned up, but creates a toggle with links to the English and Spanish version of the current page.
> Translate button implementation

- src/sass/_buttons.scss
It looks like iOS needs the `-webkit-sticky` property to work, but this fixes it for the devices I'm looking at on BrowserStack
> Add webkit prefix to sticky

- src/sass/_footer.scss
This should fix the horizontal overflow. The footer link columns were too wide for the screen size, so I increased the breakpoint
> Adjust footer nav breakpoint

- site/layouts/404.html
- src/sass/_index.scss
Closes #94. Adds really basic 404 page just so we prevent raw error messages from displaying
> Adds placeholder 404 page

- site/content/_index.md
- site/layouts/partials/footer.html
Closes #148. We just need to add `photoCredit` to any page that needs attribution, otherwise it doesn't display
> Sets up conditional for footer photo credit

- site/content/get-the-data/_index.es.md
- site/content/get-the-data/_index.md
- site/layouts/get-the-data/list.html
- src/sass/_data-form.scss
- src/sass/_inputs.scss
- src/sass/main-sass.scss
Closes #134. Adds bare-bones Get the Data form with a working endpoint. Currently redirects to the preview site. The newsletter checkbox is functional, and it uses native browser functionality for requiring and validating the email
> Add initial get data form

- gulpfile.babel.js
- package.json
- src/sass/_about-us.scss
Uses flexbox for bio instead of grid so it displays proper in IE11 (Closes #170 ).  
Updates the gulp build to autoprefix for any browsers with 1% or more usage in the US. (Fixes #163)
> Update layout on bio images

- src/sass/_subnav.scss
- Sets `justify-content` to `space-around` instead of `space-evenly` for IE11 support
Before:
After:
> Fix spacing on IE11 subnav

- site/layouts/index.html
- src/sass/_footer.scss
- src/sass/_home-pictorial-menu.scss
- src/sass/_index.scss
- src/sass/_subnav.scss
- src/sass/main-sass.scss
- Re-add focus states for accessibility, use default browser focus state but overrides color (progress on #139 )
- Set custom focus states for items in pictorial menu
- Add missing `aria-labels` on homepage social media links (closes #177 )
> Re-add focus states

- src/sass/_eviction-matters.scss
Updated to match styles from map repo. Some of the sizing is a little different to get things to fit, but the overall styles match
> Fix book buttons

- site/layouts/partials/header.html
Closes #159, progress on #152. Adds social share metadata using the same tags as on the map tool. Checks for the params "description", "fbImage", and "twImage" using defaults if it doesn't find them. I can change the description to something that makes more sense, just wasn't sure what to use
> Setup social share metadata

- site/layouts/robots.prod.txt
Closes #106. We need this so that the site can be indexed by search engines, but only in production. Merging it into cms-dev won't make it live because `robots.prod.txt` is only used on the master branch, so it's fine to merge this now
> Allow crawlers on prod

- src/sass/_home-pictorial-menu.scss
- src/sass/main-sass.scss
This fix seems to work on iOS simulator, but you should check on your iPad to make sure it works there just in case.
Closes #214
> Fix iPad double tap on pictorial menu 

- site/content/about/_index.es.md
- site/content/about/_index.md
- site/content/contact/_index.es.md
- site/content/contact/_index.md
- site/content/data-merge/_index.md
- site/content/get-the-data/_index.es.md
- site/content/get-the-data/_index.md
- site/content/help-faq/_index.es.md
- site/content/help-faq/_index.md
- site/content/methods/_index.es.md
- site/content/methods/_index.md
- site/content/updates/_index.md
- site/content/updates/blog/_index.md
- site/content/updates/events/_index.md
- site/content/updates/media/_index.md
- site/content/updates/research/_index.md
- site/content/updates/research/el-research/_index.md
- site/content/updates/research/outside-research/_index.md
- site/content/why-eviction-matters/_index.es.md
- site/content/why-eviction-matters/_index.md
- site/layouts/partials/header.html
In anticipation of search engines showing structured page links to our content, I think it's a good idea to add page-specific descriptions. However, I'd like to keep the current standardized language across social media.
Accordingly I've created a new parameter called `socialDescription` for Twitter and Facebook, and edited the the `description` parameter for each page to say more about them.
> Add page-specific descriptions for search engines

- site/content/about/_index.es.md
- site/content/about/_index.md
- site/content/contact/_index.es.md
- site/content/contact/_index.md
- site/content/data-merge/_index.md
- site/content/get-the-data/_index.es.md
- site/content/get-the-data/_index.md
- site/content/help-faq/_index.es.md
- site/content/help-faq/_index.md
- site/content/methods/_index.es.md
- site/content/methods/_index.md
- site/content/updates/_index.md
- site/content/updates/blog/_index.md
- site/content/updates/events/_index.md
- site/content/updates/media/_index.md
- site/content/updates/research/_index.md
- site/content/updates/research/el-research/_index.md
- site/content/updates/research/outside-research/_index.md
- site/content/why-eviction-matters/_index.es.md
- site/content/why-eviction-matters/_index.md
- site/layouts/partials/header.html
In anticipation of search engines showing structured page links to our content, I think it's a good idea to add page-specific descriptions. However, I'd like to keep the current standardized language across social media.
Accordingly I've created a new parameter called socialDescription for Twitter and Facebook, and edited the the description parameter for each page to say more about them.
> Add new page descriptions for structured search engine content

- site/config.toml
- Fixes link to the rankings page redirecting to the map if user is viewing in Spanish
- Fixes link to map so it remains in Spanish if user is viewing in Spanish
Closes #228
> URL encode values so Spanish links work

- site/layouts/updates/list.html
- src/sass/_lists.scss
- src/sass/_updates.scss
-Change layout to display:block
- Remove space devoted to (non-active) pagination
(This part is a slight hack -- commented out pagination because it adds a bunch of empty space if not active. There is obviously a better solution than this -- even just in CSS -- but I have to log off in a sec and just want to get this in before I do. Can fix tomorrow.)
> Mobile updates

- site/layouts/partials/pagination.html
- site/layouts/updates/list.html
Should fix the need to comment out the pagination. The `custom-pagination` div is only ever used as a wrapper around the pagination and has a fixed height, so I just pulled it into the partial
> Re-add pagination, move div into partial conditional

- src/sass/_home-splash.scss
- src/sass/main-sass.scss
Made a new breakpoint to try to reduce the excessive white space on the splash page, between about 1160—1439px, by expanding the hero width a bit. Not sure I did it in the most intelligent way, given the complex math involved. Please advise if improvements can be made here @pjsier and @Lane
> Alt splash

- site/layouts/partials/header.html
Basic cache busting by adding the build timestamp on the CSS file to ensure old asset is not served.
> CSS cache bust

- content/weekly-reports/_index.md
- static/admin/config.yml
- themes/evictionlab/assets/weekly-reports/app.css
- themes/evictionlab/layouts/weekly-reports/list.html
- allow editing meta data
- add list widget for adding links
- styling fixes for the logo links
> Weekly Reports List Updates

- .travis.yml
- netlify.toml
- themes/evictionlab/layouts/partials/agnosticbreadcrumb.html
- themes/evictionlab/layouts/partials/footer.html
- themes/evictionlab/layouts/partials/header.html
- Change `.URL` to `.Permalink` to resolve warnings
- Change `.File.Dir` to `with .File` and store directory in scratch to resolve warning
- Update `and` call in `agnosticbreadcrumb` partial to fix build error
- Update netlify / travis config to use v0.73
> hugo upgrade (0.73)

- themes/evictionlab/assets/eviction-tracking/app.css
- themes/evictionlab/assets/eviction-tracking/app.js
Changes:
- adds a class to the tooltip depending on which chart it corresponds to
- add CSS overrides to flip the colors on chart 1
> flip colors on top chart for counts tooltip
