site/config.toml, site/themes/behave/layouts/partials/header.html
updated the base of the page to '/', adjusted links to be relative from the base
=> update base URL in config and header links

gulpfile.babel.js, package-lock.json, package.json, src/sass/main-sass.scss
adds sass compiling to the gulp file.  The sass file is in `./src/sass/main-sass.scss` so that it doesn't overwrite the main.css file.
Any output can be seen in `/dist/css/main-sass.css` after a build.
=> add sass compiling to gulp file

site/themes/behave/layouts/partials/top.html, src/sass/_home-splash.scss, src/sass/_utils.scss
Make branding/nav header sticky at top of page
=> Sticky header

site/static/js/smooth-scroll.js
Closes #67. These are ballpark numbers/breakpoints, but adds the functionality
=> Add functions for customizing scroll offset

package-lock.json, package.json, yarn.lock
Should fix vulnerability warning once it's in master
=> Update moment.js, lockfiles

site/layouts/updates/single.html
=> Filter custom range for next/prev

site/layouts/partials/footer.html, site/layouts/partials/header.html, site/static/js/smooth-scroll.js
Fixes the dropdown jumping behavior, and removes extra jQuery version so that the Bootstrap `dropdown` function works
=> Fix dropdown, jQuery

site/static/js/main.js
Progress on #127. This updates the `action` attribute on the contact page whenever the select dropdown changes
=> Update form action on select change

site/layouts/partials/faq-open.html, site/layouts/partials/faqs.html, site/layouts/partials/method-open.html, site/static/js/smooth-scroll.js, src/sass/_index.scss
Closes #130.
* Opens accordion and scrolls to it on page load if in link
* Adds prefix to ID attributes
* Fixes bug where collapse icon became smaller when the accordion is expanded
=> Open accordion if linked, fix links

site/layouts/partials/book-modal.html, site/layouts/why-eviction-matters/list.html, src/sass/_dialogs.scss, src/sass/_eviction-matters.scss
Closes #107. Adds basic book modal
=> Add basic book modal

src/sass/_menu.scss
Update menu styles to match map / rankings.  Closes #174 and progress on #175 
Before:
After:
=> update menu styles to match map / rankings

src/sass/_about-us.scss
- Drops scrollable content within modals to scrollable page (default modal behavior, closes #167)
- Switches about layout to use flexbox instead of grid for IE11 compatibility. (closes #166 )
=> Fix about modals

site/layouts/partials/footer.html, site/layouts/partials/top.html
- Adds links in menu / footer for twitter / facebook
- Adds `aria-label` attributes to social icons (progress on #177)
=> Add social links to menu / footer

site/layouts/partials/about-modal.html
Closes #144 
From the first item in Spanish in the bios
=> Fix unneeded prev button on modal

site/layouts/about/list.html, site/layouts/partials/subnav.html, src/sass/_about-us.scss, src/sass/_index.scss, src/sass/_subnav.scss
- Adjusts subnav styles for consistency
Closes #100
=> Style subnav

site/config.toml, src/sass/_footer.scss
Adds Spanish translation of the menu, and increases the newsletter sign up font on mobile
=> Add Spanish menu translations, fix newsletter font

site/content/about/_index.es.md, site/content/about/_index.md, site/content/help-faq/_index.es.md, site/content/help-faq/_index.md, site/content/methods/_index.es.md, site/content/methods/_index.md, site/content/updates/_index.md, site/content/why-eviction-matters/_index.es.md, site/content/why-eviction-matters/_index.md, site/layouts/partials/header.html, src/sass/_buttons.scss, src/sass/_header.scss, src/sass/_utils.scss, src/sass/main-sass.scss
- Remove shadows from pages with subnav
- Update website box shadows to the shadows provided by Noele here: https://github.com/EvictionLab/eviction-maps/issues/674
Closes #103
=> drop shadows on pages with subnav, make shadows consistent

site/layouts/updates/single.html
The conditional and sorting had just been flipped around a bit, this should fix it
=> Fix event next/prev

site/layouts/contact/list.html, site/static/js/main.js, src/sass/_contact.scss
- Switches to radio buttons instead of select
- Adds classes to form elements so they are consistent with other form elements on the site
Closes #160
=> add form styles, use radio buttons

src/sass/_footer.scss
Boost height of footer to accommodate the "Site by" line so it doesn't push other elements to the side
=> fix footer overflow

site/content/data-merge/_index.es.md, site/content/data-merge/merge-app.es.md
- Adds a placeholder page (in English) at the Spanish URL for the Data Merge Application page to prevent the 404.
Closes #226
=> add spanish placeholder page for data merge

site/content/contact/form2.es.md, site/content/contact/form2.md, site/layouts/contact/list.html
Tested this out on staging and it works. A Spanish-speaking friend validates the placeholder text translation.
=> Add subject line to emails

src/sass/_home-pictorial-menu.scss
fixes the pictorial menu collapsing
=> set min-height on pictorial menu

site/content/updates/events/2018-05-08-UJA-Federation-NY.md, site/layouts/partials/about-modal.html, site/layouts/updates/list.html, src/sass/_about-us.scss, src/sass/_breadcrumbs.scss, src/sass/_lists.scss
- Carat fixes
- Read more links change
- Letter spacing on Events / 320
=> Style changes per Noele

site/layouts/partials/faqs.html, site/layouts/partials/footer.html, site/static/js/main.js
- Drops `accordion` prefix on links
- Allows linking directly to any question using the `faqid` in front matter
=> adjust faq to allow direct linking to questions

site/static/js/main.js
Adds some javascript to update the browser URL with the anchor of the expanded accordion item.
Closes #275
=> update URL on accordion expand

site/layouts/media-map/list.html, site/static/js/main.js
=> Header updates on media map

static/admin/index.html
- Adds a fix so the editor components render correctly
=> Fix CMS Editor Components

content/weekly-reports/_index.md, content/weekly-reports/acknowledgements.md, static/admin/config.yml
- Create link on index page
- Create page in content folder
- Update CMS to allow editing
=> Create Acknowledgements page

themes/evictionlab/static/js/covid-policy-rankings/covid-policy-rankings.js, themes/evictionlab/static/js/covid-policy-rankings/single-state-template.html, themes/evictionlab/static/js/covid-policy-rankings/states-template.html
@james-minton These are the revisions to the scorecard requested by Anne Kat. She's reviewed and approved them on a preview branch. https://5ee937989c45cb0008172eb8--eviction-lab.netlify.app/covid-policy-scorecard/#scorecard-app
I've rebased onto the latest changes in `cms-dev`, so this should be ready to merge.
=> Adds Cares Act policy and filter, updates expiry text

themes/evictionlab/assets/eviction-tracking/app.css, themes/evictionlab/assets/sass/_footer.scss
- boost footer height so funders doesn't flow to a new column
- drop y axis font size so large numbers don't exceed margins
=> style touch ups

themes/evictionlab/assets/eviction-tracking/app.css, themes/evictionlab/assets/eviction-tracking/app.js, themes/evictionlab/layouts/shortcodes/report_intro.html
- add new footnote to the table
- add new footnote to the callout in the report intro
closes #530
=> add footnotes

themes/evictionlab/assets/eviction-tracking/app.css, themes/evictionlab/assets/eviction-tracking/app.js, themes/evictionlab/layouts/shortcodes/report_chart.html
- update bar colors on first chart so "filings this year" is always red
Closes #531
=> update bar colors of first report chart

themes/evictionlab/assets/eviction-tracking/app.css, themes/evictionlab/assets/eviction-tracking/app.js, themes/evictionlab/layouts/shortcodes/report_intro.html, themes/evictionlab/layouts/shortcodes/report_map.html
- adds new pattern and shape overlay to intro figure
- adjusts layout on intro figure so footnote is inline with stats
- refactor legend item for map section to use same classes as others
=> Add CDC moratorium to report page

themes/evictionlab/assets/mapbox/mapbox.js
- use `scaleQuantize` for discrete scale
- update map colors to use the range from the discrete scale
- create separate function for rendering discrete legends, which uses svg swatches and d3 axis for ticks
=> fix: switch discrete legend to use quantize scale with nice values

content/updates/blog/jacob-post/index.md, themes/evictionlab/assets/charts/charts.css, themes/evictionlab/assets/charts/line-chart.js, themes/evictionlab/layouts/shortcodes/line-chart.html
=> Line Chart Markline
